
SELECT GETDATE() as 'Today',DATENAME(WEEKDAY,GETDATE()) as 'DayName'
SELECT GETDATE() 'Today',  DATEADD(day,-2,GETDATE()) 'Today - 2 Days'
SELECT GETDATE() 'Today', GETDATE()  -2 'Today - 2 Days'

--To convert to corresonding names using DATENAME()--
SELECT DATENAME (MONTH,'2023-04-06') As 'Month'
SELECT DATENAME (YEAR,'2023-04-06') As 'YEAR'
SELECT DATENAME (DAY,'2023-04-06') As 'DAY'
SELECT DATENAME(WEEKDAY,'2023-04-06') AS 'WEEKDAY'
SELECT DATENAME(DAYOFYEAR,'2023-04-06') AS 'DAYOFYEAR'
SELECT DATENAME(QUARTER,'2023-04-06') AS 'QUARTER'

SELECT DATEPART(MONTH,'2023-04-06') AS 'QUARTER'

--TIME IN 24 HR FORMATE 'HH:MM:SS'--
SELECT GETDATE() 'Today', CONVERT(VARCHAR(8), GETDATE(), 108) 'hh:mi:ss'

--TO GET ONLY HOUR FROM DATETIME

SELECT GETDATE() AS 'TODAY', DATEPART(HOUR,GETDATE()) AS 'HOURS'
SELECT GETDATE() AS 'TODAY',DATEPART(MINUTE,GETDATE()) AS 'MUNUTES'